<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title><?php echo $this->layout()->title; ?> - Simple Store</title>

        <meta http-equiv="Content-Language" content="pt-br" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="keywords" content="" />
    </head>
    <body>
        <?php echo $this->layout()->content; ?>
    </body>
</html>